### PR TITLE
feat: use sonic_rs

### PR DESCRIPTION
**Pull request by nanakura**
[sonic_rs](https://github.com/cloudwego/sonic-rs) is a json parse crate based on zerocopy and simd.
sonic_rs's parsing speed is much faster than serde_json.
Refer to [benchmark](https://github.com/cloudwego/sonic-rs#benchmark)

### CODE REVIEW

**Comment by VitalyAnkh** [comment]
Why closed?

**Review by eval-exec — COMMENTED** [review]
Please ignore the `.idea/*` files.

I'm looking forward to LSP-Booster's JSON parser supporting SIMD instructions. C.c. @blahgeek

**Comment by nanakura** [comment]
> Why closed?

When I migrated from serde_json to sonic_rs, the performance in the benchmark became worse, so I tried simdjson again, but the performance did not improve significantly. Here is my simdjson fork https://github.com/nanakura/emacs-lsp-booster/tree/simd-json

**Comment by eval-exec** [comment]
> > Why closed?
> 
> When I migrated from serde_json to sonic_rs, the performance in the benchmark became worse, so I tried simdjson again, but the performance did not improve significantly. Here is my simdjson fork https://github.com/nanakura/emacs-lsp-booster/tree/simd-json

Did you build lsp-booster with `RUSTFLAGS='-C target-cpu=native'`? Ref: RUSTFLAGS='-C target-cpu=native'

**Comment by nanakura** [comment]
> > > Why closed?
> > 
> > 
> > When I migrated from serde_json to sonic_rs, the performance in the benchmark became worse, so I tried simdjson again, but the performance did not improve significantly. Here is my simdjson fork https://github.com/nanakura/emacs-lsp-booster/tree/simd-json
> 
> Did you build lsp-booster with `RUSTFLAGS='-C target-cpu=native'`? Ref: https://github.com/cloudwego/sonic-rs?tab=readme-ov-file#requirementsnotes

I really didn't, it reminded me

**Comment by nanakura** [comment]
I will try again

**Comment by VitalyAnkh** [comment]
How is the benchmark now?

**Comment by nanakura** [comment]
> USTFLAGS='-C target-cpu=native'

In fact, serde_json will also have performance improvements if RUSTFLAGS='-C target-cpu=native' is used
serde_json
ce1148c189205e2eb184b13a23f7d20d

and sonic_rs
image

**Comment by VitalyAnkh** [comment]
I wonder why the results are not very promising. Could you use flamegraph to figure out why sonic-rust doesn't outperform serde_json a lot?

**Comment by nanakura** [comment]
> I wonder why the results are not very promising. Could you use flamegraph to figure out why sonic-rust doesn't outperform serde_json a lot?
> 
> Ref:
> 
> 1. [nnethercote.github.io/perf-book/profiling.html](https://nnethercote.github.io/perf-book/profiling.html)
> 2. [dendibakh/perf-book@`2.0_release` (release)](https://github.com/dendibakh/perf-book/releases/tag/2.0_release)

I tried `RUSTFLAGS='-C target-cpu=native -C symbol-mangling-version=v0' perf record -g -- cargo test --test bytecode_test --release` to  get generate a profiling file，then I get a flamegraph through https://github.com/brendangregg/FlameGraph, but the flamegraph is unreadble

**Pull request closed without merging**
